### ISSUE TITLE
Plugin causes lag over time

### ISSUE THREAD

**Issue by haydenbleasel** [tcarlsen/atom-jslint#21]
Hey mate,

Love this plugin but I've had the same problem for a while. I think there's a JSLint error queue building up or something which causes the editor to progressively become slower over time until unusable (restart fixes this). I should do some digging but I haven't really looked into how plugins work :)

**Comment by tcarlsen** [comment]
oh thats no good!

how did you determine that it is jslint that courses atom to slow down? did you disable all other plugins (except core) ?

**Comment by haydenbleasel** [comment]
Basically by installing the plugin on a fresh Atom install. Been through a few scenarios (only jslint, jslint with other plugins, etc), seems to be this plugin unfortunately causing the lag. Also, I hate to be the bearer of bad news but the "validate to save" function is broken for me on the latest version :/

**Comment by cpdeethree** [comment]
I can second confirm this bug exists. Installed it fresh on one of my projects and as I was working through the errors I noticed a significant slowdown of Atom. Possible memory leak?

**Comment by tcarlsen** [comment]
will try to look into this.. any ideas what causes this?

**Comment by haydenbleasel** [comment]
As @cpdeethree mentioned it's probably a memory leak or a cache buildup. Perhaps when you're running a lint it's being stored in an array, but that array isn't cleared before the next lint. Something like that.

**Comment by tcarlsen** [comment]
I hope this is fixed in `1.0.2`

**Comment by haydenbleasel** [comment]
Awesome, I'll keep an eye out over the next few days for performance issues and let you know!

**Comment by cpdeethree** [comment]
I tested this as well and I'm not having any further noticeable issues. Gracias!

**Comment by tcarlsen** [comment]
Glad to hear that my fix worked for you. :smile:



—
