### ISSUE TITLE
Validate on Save doesn't work with 1.0.1

### ISSUE THREAD

**Issue by haydenbleasel** [tcarlsen/atom-jslint#22]
Basically what the title says. Worked on all previous versions, stopped working with the update. Checked the preferences, seems fine.

**Comment by tcarlsen** [comment]
hmmmmm its working on my end....

**Comment by tcarlsen** [comment]
try re-enable the option and do a reload `ctrl+alt+cmd+l` the config file for atom has changed since the new API maybe something is hanging there?

**Comment by haydenbleasel** [comment]
@tcarlsen If I reload using `ctrl+alt+cmd+l` and then save, it works. Unfortunately if I change file, the process needs to be repeated for lint to work.

**Comment by tcarlsen** [comment]
oh so it only works one time per refresh?

**Comment by haydenbleasel** [comment]
Works unlimited times after a refresh but dies when you change file. Wrote a quick flow thing:

```
1) ctrl-s: Nothing happens (should lint)
2) ctrl-alt-cmd-l: Refresh Atom
3) ctrl-s: Lints on save!
4) ctrl-s: Lints on save again! All good.
5) Open a new file, go back to 1
```

**Comment by tcarlsen** [comment]
please test if my fix is working?

**Comment by haydenbleasel** [comment]
Yep awesome, totally works again now!

**Comment by tcarlsen** [comment]
good to hear.. thx for reporting and using my package
