### ISSUE TITLE
Make the used lint version  configurable.

### ISSUE THREAD

**Issue by bbroeksema** [tcarlsen/atom-jslint#23]
Browsing through the plugin code I saw that it always uses the latest version:

jsLint = require("jslint").load("latest")

In some contexts I'm bound to a particular version. Can this be made configurable?

**Comment by tcarlsen** [comment]
That's an awesome idea!!!

Will look into this asap 



—

**Comment by bbroeksema** [comment]
Cool, looking forward to it!

**Comment by tcarlsen** [comment]
added in `1.1.0` but change og jslint version needs a reload of Atom to take effect
