### ISSUE TITLE
Add es6 support

### ISSUE THREAD

**Issue by hhsnopek** [tcarlsen/atom-jslint#27]
Would be great for es6 support :smile:

**Comment by tcarlsen** [comment]
will look into it..

**Comment by tcarlsen** [comment]
for now it does not look like JSLint is supporting es6, so I can't really do anything about it.

https://github.com/douglascrockford/JSLint/pull/163

**Comment by hhsnopek** [comment]
As I look closely now, I was using jshint not jslint - I'm sorry for the hassle!

**Comment by tcarlsen** [comment]
No problem m8 :smile:

**Comment by bbroeksema** [comment]
Maybe time to reopen? The current jslint seems to be a rewrite with support for es6.

**Comment by warren-lockhart** [comment]
The current version of jslint supports es6 features with the es6: true option. With the old version of jslint currently used by atom-jslint, js code which uses es6 will not be recognised.

**Comment by tcarlsen** [comment]
I will take a look as soon as I have time, If any1 want to take a look a PR is more then wellcome

**Comment by tcarlsen** [comment]
Will you guys please test out the new [es6](https://github.com/tcarlsen/atom-jslint/tree/es6) branch??

You need to select es6 in the jslint version dropdown and reload atom to test this

**Comment by zdennis** [comment]
I get an error about loading `atom-message-panel`. I installed it, but the error persisted on restarting atom.

**Comment by tcarlsen** [comment]
you need to navigate to jslint abd run `npm install` to get atom-messag-panel when downloading this package manually

**Comment by optimisme** [comment]
I have cloned the repository, changed to es6 branch and then 'apm install jslint' but es6 is not showing up at the 'jslint' version list. How can I test es6 branch?

**Comment by haydenbleasel** [comment]
@tcarlsen ^ bump.
<img width="697" alt="screenshot 2015-11-07 23 57 00" src="https://cloud.githubusercontent.com/assets/4142719/11019382/45b32290-85ab-11e5-99f3-2a18ea9e3d8f.png">

**Comment by tcarlsen** [comment]
1.5.0 is now out with ES6 support

 - Update jslint package
 - Go to settings and select es6 as your jslint version
 - Restart Atom
 - Set es6 to true in your .jslintrc file
