### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by StiveAZ** [tcarlsen/atom-jslint#28]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Stive\AppData\Local\atom\app-0.187.0\resources\app\src\atom.js:54:11)
Object.setFileClasses (C:\Users\Stive\.atom\packages\jslint\node_modules\atom-keymap-plus\index.js:9:13)
```

**Comment by tcarlsen** [comment]
Thx fir reporting. I will look into it on Monday

**Comment by tcarlsen** [comment]
looks like you're using a old version of jslint. the error is coming from atom-keymap-plus which jslint is not using anymore.

try uninstalling and reinstalling jslint
