### ISSUE TITLE
Bug when tracking subscriptions

### ISSUE THREAD

**Issue by bichiliad** [tcarlsen/atom-jslint#36]
Full disclaimer, I've only started hacking on Atom again recently, so I could be totally wrong about this, but you may not be tracking your subscriptions properly. 

https://github.com/tcarlsen/atom-jslint/blob/master/lib/main.coffee#L37

`atom.workspace.observeTextEditors` passes every editor (and future editor) to that anonymous function, which then generates a disposable for each one, which then replaces the previous one saved in `subscriptions.onSave`. 

It also may have the secondary effect of attaching a bunch of extra event handlers, since every time `jshint.validateOnSave` changes, it attaches a new listener, which is called every time a new editor is added (`atom.workspace.observeTextEditors` also returns a disposable, which you don't seem to track). I haven't looked into that explicitly, though. 

I think your best bet would be to track both the `observeTextEditors` disposable as well as the `onDidSave` disposables.

**Comment by tcarlsen** [comment]
I believe your right, the use of `atom.workspace.observeTextEditors` was a "quick fix" to be 1.0 ready.

at the moment Im super busy with the election going on in denmark, but if you have time I will love to merge a PR?

**Comment by bichiliad** [comment]
I have a little bit of time, I could take a look at it today. After today though, I'm on vacation for a while. I'll get something together and send you a PR. 






On Wed, May 27, 2015 at 10:58 PM -0700, "Thomas Carlsen" <notifications@github.com> wrote:












I believe your right, the use of atom.workspace.observeTextEditors was a "quick fix" to be 1.0 ready.



at the moment Im super busy with the election going on in denmark, but if you have time I will love to merge a PR?
