### ISSUE TITLE
Link to JSLint options is broken

### ISSUE THREAD

**Issue by BramVanroy** [tcarlsen/atom-jslint#39]
In the read-me the link to JSLint options is broken. It refers to http://www.jslint.com/lint.html#options but that address returns a 404. I have been looking for better documentation on JSLint, but I can't seem to find a lot. I do find some more on JSHint, but I assume those are two different things.

(I have been looking in the options because I want to disable the message `'$' was used before it was defined.`)

**Comment by tcarlsen** [comment]
Thx for the heads up. Will update the README. 

New link: http://www.jslint.com/help.html
Your case with '$' can be solved two ways. 

1. In the top of your js file write '/*global $*/
2. Make a .jslintrc file (to cover all project js filed) and write 
'''
{
      "predef": [
        "angular",
        "$"
    ]
}
'''
You can also take a look at the file https://github.com/tcarlsen/atom-jslint/blob/master/.jslintrc-example

**Comment by BramVanroy** [comment]
Thanks for the quick reply. I added the example to `C:\Users\Bram\.atom` and renamed it `.jslintrc` but I get the same message. Did I put it in the wrong directory?

**Comment by tcarlsen** [comment]
You need to place it in your project root (the folder you are opening in atom)

**Comment by BramVanroy** [comment]
Hm, this doesn't seem to work. This is my `.jslintrc` file:
````json
{
    "indent": 2,
    "maxerr": 9999,
    "predef": [
        "$",
        "document"
    ]
}
````

I added "html-trees" (below) in Atom.
![Atom](https://cloud.githubusercontent.com/assets/2779410/8396819/b685f6da-1db6-11e5-8a2a-a54173d14675.PNG)

This ought to work, right?

**Comment by tcarlsen** [comment]
try opening the Developer tools panel and switch to console.

run  `atom.project.getPaths()[0]` and lets see what you get

**Comment by BramVanroy** [comment]
````
atom.project.getPaths()[0]
"E:\xampp\htdocs\bramvanroy\projects\html-trees"
````

**Comment by BramVanroy** [comment]
Okay, all of a sudden without changing anything, this works. This is extremely strange. I still get the annoying `Move 'var' declarations to the top of the function.` in a for loop but that's something else. Closing.

**Comment by BramVanroy** [comment]
EDIT: reopening because the link in the readme hasn't changed yet.

**Comment by tcarlsen** [comment]
`vars: true`
