### ISSUE TITLE
Seems to have problems with template strings.

### ISSUE THREAD

**Issue by Karlgamer** [tcarlsen/atom-jslint#40]
var template = `<div class='tile' style='top: ${top}px; left: ${left}px;'></div>`;

this code gets me

Unexpected '`'.

is error

**Comment by tcarlsen** [comment]
how are you even getting this error? `jslint` should only run inside a `.js` file

**Comment by Karlgamer** [comment]
I'm using it with a .js file.

I'm trying to use the es6 template strings feature. You use the back-tick(It's on the same key as the tilde) character to enclose your string instead of single or double quotes.

It's a useful feature because you can do this:
var name = "Bob",
age =  16,
hColor = "blue";

console.log(`${name} is ${age}, and has ${hColor} hair.`);
//Bob is 16, and has blue hair.

instead of:

console.log(name + " is " + age + ", and has " + hColor + " hair.");
//bob is 16, and has blue hair.
It works fine, and it's error free in Crockfords jslint when I click the "assume.. ES6."

Is this something I can set in my .jslintrc file?

I tried adding: "es6": true, 

but it didn't do anything.

**Comment by Karlgamer** [comment]
I see you have to escape the back-tick in github apparently

**Comment by tcarlsen** [comment]
es6 is not yet enabled see #27

**Comment by tcarlsen** [comment]
please go test the new [es6](https://github.com/tcarlsen/atom-jslint/tree/es6) branch??

You need to select es6 in the jslint version dropdown and reload atom to test this

**Comment by pyvim** [comment]
Hello. +1 to problem.
@tcarlsen, I have in the JSLint version dropdown `latest` and versions by dates.

**Comment by tcarlsen** [comment]
1.5.0 is now out with ES6 support

 - Update jslint package
 - Go to settings and select es6 as your jslint version
 - Restart Atom
 - Set es6 to true in your .jslintrc file
