### ISSUE TITLE
Incorrect line/character numbers when ES6 is enabled

### ISSUE THREAD

**Issue by akivajgordon** [tcarlsen/atom-jslint#43]
With the ES6 option enabled, the line and character numbers that are reported are off by 1.

This appears to be due to a change in the `jslint` report when ES6 is enabled. Using this silly file:
```
$ echo 'hi' > /tmp/foo.js
```

here are the results **without** the `es6` option:
```
$ jslint /tmp/foo.js

/tmp/foo.js
 #1 'hi' was used before it was defined.
    hi // Line 1, Pos 1
 #2 Expected ';' and instead saw '(end)'.
    hi // Line 1, Pos 3
```

compared with the results **with** the `es6` option:
```
$ jslint --edition=es6 /tmp/foo.js 

/tmp/foo.js
 #1 Undeclared 'hi'.
    hi // Line 0, Pos 0
 #2 Expected ';' and instead saw '(end)'.
    hi // Line 0, Pos 2
```

Notice how the line and character markers are off by 1. This package needs to compensate by adding 1 when reporting it in Atom.

**Comment by tcarlsen** [comment]
thx for reporting

**Comment by tcarlsen** [comment]
`1.5.1` is now out with this update :smile:
